import Head from "next/head";

import * as Styled from "./styled";

const Home = () => {
	return (
		<div>
			<Head>
				<title>Doces Dias</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<Styled.Title>oi</Styled.Title>
			<p>teste do deploy</p>
		</div>
	);
};

export default Home;
